import { ArrowRight, Atom, CircuitBoard, Crosshair, GraduationCap, Mail, Radar, Satellite, Sparkles } from 'lucide-react'

const email = 'info@qbitflow.com'
const quote = (subject: string) => `mailto:${email}?subject=${encodeURIComponent(subject)}`

const nav = [
  ['Products', '#products'], ['Projects', '#projects'], ['Engineering', '#engineering'], ['Training', '#training'], ['Who we are', '#team']
]

const products = [
  { title: 'Reliable Alkali Metal Sources (RAMS)', image: '/briefing/image2.png', secondary: '/briefing/image5.png', subject: 'Quote request for RAMS', text: 'Our reliable alkali metal sources (RAMS) provide a stable, high-purity supply of atomic vapor for quantum and atomic physics applications. Designed for long lifetime, reproducible flux, and reliable integration into ultra-high vacuum systems, they ensure consistent performance in demanding research and sensing environments.' },
  { title: 'Preparation Chamber System', image: '/briefing/image3.jpg', subject: 'Quote request for Preparation Chamber System', text: 'Our preparation chamber for 2D+ MOT systems enables efficient pre-cooling and transport of atomic beams under ultra-high vacuum conditions. Optimized for high flux, optical access, and stable operation even in harsh environments, it provides a reliable atomic source stage for advanced quantum sensing and cold atom experiments.' }
]

const projects = [
  { title: 'ESA-BIC', image: '/briefing/image6.png', logo: '/briefing/image7.jpeg', text: 'The ESA BIC Incubation Program Northern Germany promotes and supports start-ups that develop an innovative technology or service with a clear space connection. QBITFLOW aims to develop a space-suitable hybrid inertial sensor for navigation purposes. As part of the development roadmap QBITFLOW develops a modular ultra-high vacuum system, which is a key technology for quantum sensors. In the framework of this incubation QBITFLOW builds a demonstrator of one important component of the vacuum system — an improved preparation chamber to pre-cool atoms in a 2D magneto optical trap.' },
  { title: 'Modular Vacuum System', image: '/briefing/image4.png', text: 'We aim to develop a next-generation modular ultra-high vacuum (UHV) platform designed to accelerate research and industrial development in quantum sensing and neutral-atom quantum computing. By combining scalable architecture, high optical access, and flexible integration capabilities, the system enables rapid prototyping and reliable operation of advanced neutral-atom experiments. The modular approach reduces development time, simplifies customization, and supports applications from precision sensors to scalable quantum processors.' },
  { title: 'Hybrid Quantum Inertial Sensor', image: '/briefing/image8.png', text: 'Looking ahead, we are advancing toward a fully commercial hybrid inertial sensor that combines quantum precision with classical robustness. This next-generation system will deliver unprecedented accuracy and stability for navigation and motion sensing—bringing quantum-enhanced performance into real-world industrial and mobility applications.' }
]

const team = [
  { name: 'Roland Becker', role: 'CEO & Co-Founder', image: '/briefing/image11.jpeg', bio: 'Founder and CEO of the JUST ADD AI Group, Artificial Intelligence Specialist, Entrepreneur, and host of the THINK REACTOR Podcast.' },
  { name: 'Prof. Hansjörg Dittus', role: 'Co-Founder', image: '/briefing/image12.jpeg', bio: 'Former board member of the German Aerospace Center (DLR). Professor for Space Systems at the University of Bremen. Specialized in Quantum Systems in Space.' },
  { name: 'Dr.-Ing. Jens Grosse', role: 'CTO & Co-Founder', image: '/briefing/image13.jpeg', bio: 'Co-Founder of QBITFLOW and Group Leader of the Space Technologies Department at the Center Of Applied Space Technology And Microgravity (ZARM) at the University of Bremen. Expert for Quantum Sensors, Experiments and Enabling Technologies on Ground and in Space.' },
  { name: 'Samuel Hill', role: 'Co-Founder', image: '/briefing/image14.jpeg', bio: 'Senior Consultant at the German Research Center for Artificial Intelligence (DFKI) Robotics Innovation Center. 20+ years in photonic based hardware-software development and commercialization.' }
]

function SectionTitle({ eyebrow, title, text }: { eyebrow: string; title: string; text?: string }) {
  return <div className="mx-auto mb-12 max-w-3xl text-center"><p className="mb-3 text-sm font-semibold uppercase tracking-[.3em] text-cyan">{eyebrow}</p><h2 className="text-3xl font-semibold tracking-tight text-white md:text-5xl">{title}</h2>{text && <p className="mt-5 text-lg leading-8 text-slate-300">{text}</p>}</div>
}

export default function Home() {
  return <main className="min-h-screen overflow-hidden bg-ink text-slate-100">
    <div className="fixed inset-0 -z-10 tech-grid opacity-70" />
    <div className="fixed inset-0 -z-10 quantum-field" />
    <header className="sticky top-0 z-50 border-b border-cyan/20 bg-ink/80 backdrop-blur-xl">
      <div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4">
        <a href="#home" className="flex items-center gap-3"><img src="/briefing/image1.png" alt="QBITFLOW" className="h-7 w-auto invert" /></a>
        <nav className="hidden gap-6 text-sm text-slate-300 md:flex">{nav.map(([label, href]) => <a key={href} href={href} className="transition hover:text-white">{label}</a>)}</nav>
        <a href={`mailto:${email}`} className="tech-button rounded-full px-4 py-2 text-sm font-semibold">Get in touch</a>
      </div>
    </header>

    <section id="home" className="relative mx-auto grid max-w-7xl items-center gap-12 px-5 py-24 md:grid-cols-[1.05fr_.95fr] md:py-32">
      <div className="absolute left-1/2 top-16 -z-10 h-96 w-96 rounded-full bg-cyan/20 blur-3xl" />
      <div><p className="mb-5 inline-flex items-center gap-2 rounded-full border border-cyan/30 bg-cyan/5 px-4 py-2 text-sm text-cyan shadow-[0_0_30px_rgba(0,224,255,.12)]"><Atom size={16}/> Quantum sensing // UHV systems // Field-ready engineering</p><h1 className="max-w-4xl text-5xl font-semibold leading-tight tracking-tight text-white md:text-7xl">We turn cutting-edge quantum research into real-world impact.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-300">Born out of university research, QBITFLOW develops next-generation technologies for quantum sensors and transfers them from the lab into practical applications. We combine deep scientific expertise with engineering excellence to transform fundamental breakthroughs into robust, scalable solutions.</p><div className="mt-9 flex flex-wrap gap-4"><a href="#products" className="tech-button inline-flex items-center gap-2 rounded-full px-6 py-3 font-semibold">Explore products <ArrowRight size={18}/></a><a href="#projects" className="rounded-full border border-cyan/25 bg-white/[.03] px-6 py-3 font-semibold text-white transition hover:border-cyan hover:text-cyan">See projects</a></div></div>
      <div className="tech-panel relative rounded-[2rem] p-4"><div className="absolute right-6 top-6 z-10 rounded-full border border-cyan/30 bg-ink/70 px-3 py-1 text-xs uppercase tracking-[.25em] text-cyan">Prototype stack</div><div className="grid gap-4"><img src="/briefing/image2.png" alt="Alkali metal source transport case" className="h-56 w-full rounded-3xl object-cover"/><div className="grid grid-cols-2 gap-4"><img src="/briefing/image3.jpg" alt="Preparation chamber" className="h-40 rounded-3xl object-cover"/><img src="/briefing/image4.png" alt="Modular vacuum system" className="h-40 rounded-3xl object-contain img-pad p-3"/></div></div></div>
    </section>

    <section className="border-y border-cyan/15 bg-cyan/[.025] px-5 py-10"><div className="mx-auto grid max-w-7xl gap-6 text-center md:grid-cols-3"><p className="metric"><Crosshair className="mx-auto mb-3 text-cyan"/><b>Ultra-precise measurements</b><br/><span className="text-slate-400">Navigation, geophysics and infrastructure monitoring.</span></p><p className="metric"><CircuitBoard className="mx-auto mb-3 text-cyan"/><b>Lab-to-field engineering</b><br/><span className="text-slate-400">From concept to deployment.</span></p><p className="metric"><Radar className="mx-auto mb-3 text-cyan"/><b>Robust quantum systems</b><br/><span className="text-slate-400">Built for demanding environments.</span></p></div></section>

    <section id="products" className="mx-auto max-w-7xl px-5 py-24"><SectionTitle eyebrow="Products" title="Components that power next-generation quantum technologies" text="High-quality alkali metal sources and advanced vacuum system components for quantum experiments and operation in harsh environments." />
      <div className="grid gap-8">{products.map((p) => <article key={p.title} className="tech-panel grid items-center gap-8 rounded-[2rem] p-6 md:grid-cols-2"><div className="grid gap-4 md:grid-cols-2"><img src={p.image} alt={p.title} className="h-72 w-full rounded-3xl object-contain img-pad p-4"/>{p.secondary && <img src={p.secondary} alt="RAMS hardware" className="h-72 w-full rounded-3xl object-cover"/>}</div><div><p className="mb-3 text-sm uppercase tracking-[.25em] text-cyan">Product system</p><h3 className="text-3xl font-semibold text-white">{p.title}</h3><p className="mt-5 text-lg leading-8 text-slate-300">{p.text}</p><a href={quote(p.subject)} className="tech-button mt-7 inline-flex items-center gap-2 rounded-full px-5 py-3 font-semibold"><Mail size={18}/> Request a quote</a></div></article>)}</div>
    </section>

    <section id="projects" className="bg-white/[.03] px-5 py-24"><div className="mx-auto max-w-7xl"><SectionTitle eyebrow="Projects" title="Research projects for field-ready quantum systems" text="Together with academic and industrial partners, we develop new architectures and translate scientific breakthroughs into scalable solutions." />
      <div className="grid gap-7">{projects.map(p => <article key={p.title} className="tech-panel grid gap-8 rounded-[2rem] p-6 md:grid-cols-[.8fr_1.2fr]"><div><img src={p.image} alt={p.title} className="h-80 w-full rounded-3xl object-contain img-pad p-4"/>{p.logo && <img src={p.logo} alt="ESA Business Incubation Centre Northern Germany" className="mt-5 rounded-2xl bg-white p-3"/>}</div><div className="self-center"><h3 className="text-3xl font-semibold text-white">{p.title}</h3><p className="mt-5 text-lg leading-8 text-slate-300">{p.text}</p></div></article>)}</div></div></section>

    <section id="engineering" className="mx-auto grid max-w-7xl items-center gap-10 px-5 py-24 md:grid-cols-2"><div className="grid gap-5"><img src="/briefing/image9.png" alt="Custom vacuum component" className="rounded-[2rem] object-cover"/><img src="/briefing/image8.png" alt="Hybrid sensor concept" className="rounded-[2rem] object-contain img-pad p-4"/></div><div><p className="mb-3 text-sm font-semibold uppercase tracking-[.3em] text-cyan">Engineering Solutions</p><h2 className="text-4xl font-semibold text-white md:text-5xl">Custom components and subsystem designs tailored to your needs.</h2><p className="mt-6 text-lg leading-8 text-slate-300">With engineering expertise from the design, assembly and test of quantum sensors for challenging applications in demanding environments, we provide individual vacuum and opto-mechanical parts as well as fully integrated subsystems.</p><a href={`mailto:${email}?subject=${encodeURIComponent('Engineering solutions request')}`} className="tech-button mt-8 inline-flex items-center gap-2 rounded-full px-6 py-3 font-semibold">Challenge us <ArrowRight size={18}/></a></div></section>

    <section id="training" className="bg-white/[.03] px-5 py-24"><div className="mx-auto grid max-w-7xl items-center gap-10 md:grid-cols-[.8fr_1.2fr]"><img src="/briefing/image10.jpg" alt="Quantum technology training group" className="rounded-[2rem]"/><div><p className="mb-3 inline-flex items-center gap-2 text-sm font-semibold uppercase tracking-[.3em] text-cyan"><GraduationCap size={18}/> Training & Education</p><h2 className="text-4xl font-semibold text-white md:text-5xl">Practical quantum sensor training for technical teams.</h2><p className="mt-6 text-lg leading-8 text-slate-300">The field of quantum technologies is growing rapidly, demanding trained personnel for design, integration, test and operation of quantum sensor systems. We offer practical workshops, system-level training, and application-focused courses that empower teams to design, operate, and advance quantum sensing technologies with confidence.</p></div></div></section>

    <section id="team" className="mx-auto max-w-7xl px-5 py-24"><SectionTitle eyebrow="Who we are" title="Scientists, engineers and entrepreneurs" text="An interdisciplinary founding team with experience across quantum sensors, aerospace, AI, robotics and technology commercialization." /><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">{team.map(m => <article key={m.name} className="tech-panel rounded-[2rem] p-5"><img src={m.image} alt={m.name} className="aspect-square w-full rounded-3xl object-cover"/><h3 className="mt-5 text-xl font-semibold text-white">{m.name}</h3><p className="text-cyan">{m.role}</p><p className="mt-3 text-sm leading-6 text-slate-300">{m.bio}</p></article>)}</div></section>

    <footer className="border-t border-white/10 px-5 py-12"><div className="mx-auto flex max-w-7xl flex-col gap-6 md:flex-row md:items-center md:justify-between"><img src="/briefing/image1.png" alt="QBITFLOW" className="h-7 w-fit invert"/><p className="text-sm text-slate-400">QBITFLOW GmbH // Quantum Solutions to real world problems</p><div className="flex gap-4 text-sm text-slate-300"><a href="/imprint">Imprint</a><a href="/data-protection">Data Protection</a></div></div></footer>
  </main>
}
